<!-- 
<h4>Dernier discours :</h4>
<h5>J.-L. Melenchon, le 07 décembre 2016 (Blog)</h5>
<p>
Tomber malade : un nouveau luxe
</p><p>
Non, ce n’est pas un procès d’intention. François Fillon est le candidat des assureurs contre la Sécurité sociale. C’est ce qui ressort de la lecture de son programme.  Tout le monde pourra aller vérifier ce que je vais relever. Le système Fillon repose sur le recul des remboursements par la Sécurité sociale et l’encouragement aux assureurs privés. Un autre indice nous a été donné la presse. France Inter affirme ainsi que François Fillon aurait déjà choisi son futur ministre de l’Économie et des Finances en cas de victoire à la présidentielle. Il nommerait à Bercy Henri de Castries, l’ancien PDG de l’assureur privé Axa pendant 16 ans ! Ce ne peut être un hasard. Henri de Castries n’a quitté la présidence de ce groupe qu’il y a quelques mois, pour devenir administrateur de la banque HSBC. Précisons, pour situer les perceptions de la vie que peut avoir le personnage : lors de sa dernière année chez Axa, en 2015, il gagnait 5,4 millions d’euros de salaire ! Que peut-il comprendre aux raisons des 30 % de gens qui n’osent plus se soigner parce qu’une ordonnance, ça coûte trop cher… Le conflit d’intérêt serait immense si ce personnage devenait demain ministre des Finances chargé de faire voter le budget de la Sécurité sociale et la fiscalité des clients des assurances privées.
</p><p>
Reste une évidence, Castries ou pas : le programme de François Fillon, c’est ouvertement et officiellement le début de la fin de la Sécurité sociale. À commencer par la fin de l’assurance maladie pour tous. Fillon l’a écrit noir sur blanc dans son programme pour la santé. Il veut « focaliser l’assurance publique universelle (c’est-à-dire la Sécu) sur des affections graves ou de longue durée, et l’assurance privée sur le reste ». Vous voilà prévenus. Le système collectif et solidaire actuel où chacun cotise selon ses moyens et reçoit selon ses besoins serait donc abandonné. Ou plus exactement limité aux seules « affections graves ». Et le reste ? Ce sera nécessairement à charge d’une assurance complémentaire. Bien sûr, pour faire bonne figure, Fillon dit que « les moins favorisés ne pouvant accéder à l’assurance privée bénéficieront d’un régime spécial de couverture accrue » mais sans dire qui cela concernera. Et quand on l’entend critiquer l’assistanat, on le voit mal élargir l’accès à la Couverture maladie universelle, la CMU. Il faudrait donc payer plus cher pour être moins remboursés quand on va chez le médecin ou chez le pharmacien et les inégalités se multiplieraient.
</p><p>
C’est aussi un programme absurde du point de vue sanitaire. Car les « affections graves » ne le sont pas toujours depuis le début. Et les autres affections ne sont pas bénignes de la même manière pour tous, ni suivant les âges. Mais dans tous les cas, en se soignant de bonne heure, on évite souvent bien des complications et des aggravations. Il est donc totalement stupide de moins rembourser les soins courants. Le renoncement aux soins des plus pauvres fera exploser les dépenses de prises en charge aux urgences ou une fois les maladies devenues plus graves, c’est-à-dire plus douloureuses et dangereuses pour les patients et plus chères à prendre en charge.
</p><p>
La santé n’est pas le seul domaine où François Fillon veut donner la main aux assureurs privés. Il tient le même discours à propos de la prise en charge du vieillissement de la population. En matière de retraite, il propose de repousser l’âge de départ à 65 ans. Mais aussi de « mettre en place un étage de retraite par capitalisation », c’est-à-dire où chacun paye dans son coin une cotisation privée avec un cadeau fiscal à la clef. Naturellement cela n’a jamais garanti un montant de retraite où que ce soit dans le monde où ce régime est appliqué. C’est si vrai que partout où le retour dans le régime général a été proposé aux assurés et partout où le cadeau fiscal a été supprimé, le régime de capitalisation s’est volatilisé. À quoi bon recommencer une expérience qui ne marche pas ?
</p><p>
Face à la dépendance aussi, François Fillon récuse le mécanisme de la  solidarité et prône le chacun pour soi. Son programme prévoit d’« encourager la généralisation d’une couverture assurantielle dépendance privée sur une base volontaire par des contrats labellisés avec des incitations fiscales qui permettront aux particuliers de déduire de leurs impôts une part de leur cotisation à une assurance dépendance ». Ceux qui peuvent payer auront droit à une assurance contre la dépendance ? Et les autres ? Continueront-ils à souffrir en silence comme aujourd’hui face au manque de places accessibles dans des établissements pour personnes âgées dépendantes ? Devront-ils faire appel à la charité ? Les familles continueront-elles à se saigner en argent, temps et énergie pour aider les parents ?
</p><p>
Ce programme a un but. Transférer au privé les milliards d’euros de cotisations maladie et retraite aujourd’hui gérés par la Sécurité sociale et offrir aux assureurs les milliards en vue pour financer la dépendance des personnes âgées. Car c’est un marché où certains voient bien quels juteux profits sont possibles. En cela, la rumeur selon laquelle Henri de Castries deviendrait ministre de l’Économie et des Finances de François Fillon est éclairante. Henri de Castries, est un symbole de l’oligarchie. Il coche toutes les cases de la caste : issu de la noblesse, diplômé de l’ENA dans la même promotion « Voltaire » que François Hollande dont il est l’ami, hier soutien de Nicolas Sarkozy, aujourd’hui ami de François Fillon. Il a aussi été « Young leader » de la French American foundation en 1994, et préside le comité de direction du groupe Bildelberg, qui réunit le gratin de l’oligarchie mondiale.
</p><p>
Nous défendons un tout autre modèle : la sécurité sociale. Le programme l’Avenir en commun prévoit tout le contraire de M. Fillon. Nous proposons d’améliorer la prise en charge des soins par la Sécurité sociale jusqu’à leur remboursement à 100%. Nous voulons rétablir la retraite à 60 ans, réduire la durée de cotisation exigée pour avoir une retraite complète et renforcer le régime de retraite solidaire par répartition. Et face à la dépendance, nous défendons notamment la construction de 50 000 places en établissements pour prendre en charge les personnes dans le besoin dans un réseau public et abordable, et la baisse de ce qui reste à la charge des familles pour les personnes qui continuent de vivre chez elle.
</p><p>
Ce modèle est plus juste et moins coûteux. Plus juste car dans le système de la sécurité sociale, le montant des cotisations ne dépend pas de l’âge ni de l’état de santé et que la protection dont on bénéficie ne dépend pas de ses moyens financiers mais de ses besoins : chacun est remboursé de la même façon par exemple. Chacun a un aperçu de ce qu’est un système d’assurance privée individuelle, à travers sa complémentaire santé s’il a les moyens de s’en payer une. Surtout, la Sécu c’est moins cher ! Il suffit de comparer les dépenses de santé entre la France et les États-Unis. En France, ces dépenses de santé représentent 11% de la richesse annuelle du pays. Elles sont essentiellement supportées par l’assurance maladie. Aux États-Unis, les dépenses de santé sont essentiellement privées. Et elles coûtent plus cher puisqu’elles atteignent 16,5% de la richesse du pays. Tout cela pour des résultats sanitaires mauvais là où la France reste une référence malgré les mauvais coups portés à notre système solidaire et à l’hôpital public.
 -->
 
 
<?php 
echo "<h4>Dernier discours enregistré :</h4>";
echo "<h5>" . $candidat . ", le " . $pretty_print_date ." - " .  $type. " - " . $source . "</h5>"; 
foreach ($text as $line) {
	echo $line;
} 

?>